# Generated by Django 5.0.4 on 2024-04-21 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('ownership_status', models.BooleanField(default=False, verbose_name='Ownership Status')),
                ('confirmation_status', models.BooleanField(default=False, verbose_name='Confirmation Status')),
                ('images', models.ImageField(blank=True, null=True, upload_to='land_images')),
                ('document', models.FileField(blank=True, null=True, upload_to='land_documents')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
            },
        ),
    ]
