# Generated by Django 5.0.4 on 2024-04-21 13:04

import django.db.models.deletion
import surveyors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('house_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='surveyor_images')),
                ('resume', models.FileField(blank=True, null=True, upload_to='surveyor_resumes')),
                ('is_potential_seller', surveyors.models.PotentialSellerField(default=False, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
